pgctl/cli.py
pgctl/service.py
pylintrc
tests/conftest.py
tests/examples/date/playground/date/run
tests/integration/cli.py
tests/integration/examples.py
tests/unit/service.py

This adds a new config option `pghome` which defaults to `$XDG_RUNTIME_DIR/pgctl` (where `XDG_RUNTIME_DIR` defaults to `~/.run` if not set).
The structure looks something like:
```
$ tree ~/.run
/nail/home/ckuehl/.run
└── pgctl
└── nail
└── home
└── ckuehl
└── proj
└── some_project
└── playground
├── relode
│   └── supervise
│       ├── control
│       ├── lock
│       ├── ok
│       └── status
├── uwsgi
│   └── supervise
│       ├── control
│       ├── lock
│       ├── ok
│       └── status
└── watch-templates
└── supervise
├── control
├── lock
├── ok
└── status
13 directories, 12 files
```

Symlink service directories into $XDG_RUNTIME_DIR

---

pgctl/cli.py
pgctl/daemontools.py

This moves daemontools-related things to a separate `daemontools` module. It's entirely cut/paste and fixing imports.
This helps keep `cli` only for cli-specific stuff.

Move daemontools commands to separate module

---

.coveragerc
pgctl/cli.py
pgctl/functions.py
tests/conftest.py
tests/spec/cli.py
tests/spec/config.py
tests/spec/configsearch.py
tests/spec/examples.py
tests/testing/__init__.py

One less TODO, and fixed a few spots where we forgot to pin stderr and/or returncode.

reduce boilerplate by adding assert_command()

---

pgctl/service.py
tests/examples/slow-shutdown/playground/sweet/run
tests/spec/examples.py

rework the lock timeout logic to be more resilient/accurate when lsof can take .9 seconds

slow-shutdown more reliable in slow-lsof case

---

CI/Dockerfile
Makefile
TODO.md
pgctl/__init__.py
pgctl/cli.py
pgctl/functions.py
pgctl/fuser.py
tests/spec/dirty_tests.py
tests/spec/fuser.py
tests/testing/pty.py
tests/unit/functions.py

This removes the nasty system dependency, and brings our assert-down time from 3 seconds to 0.2 seconds on my dev machine.

our very own fuser function

---

pgctl/__init__.py
pgctl/service.py
tests/spec/debug.py

We don't need to supervise a process running in the foreground.

Remove supervise for debug

---

pgctl/cli.py
pgctl/service.py
tests/examples/pre-start-hook/playground/pre-start
tests/examples/pre-start-hook/playground/sweet/run
tests/spec/examples.py

It is a very common requirement to want to require some build step before `pgctl` is invoked. For example, in a Python project, it would be great if we could force a run of venv-update (this should be very fast in the no-op case, and in the non-no-op case, you needed to run it anyway).
We currently hack this by running some make targets in services, but potentially all of the services could require these make targets, and we can't put it in all of them. Putting the make targets into the services also means we have to use unreasonable timeouts to account for non-no-op cases. These make regular development difficult.
With this change, you just throw your pre-start script at `playground/pre-start`.

Add support for a playground-wide "pre-start" hook

---

pgctl/cli.py
pgctl/service.py
tests/examples/post-stop-hook/playground/A/run
tests/examples/post-stop-hook/playground/B/run
tests/examples/post-stop-hook/playground/post-stop
tests/spec/examples.py
tests/unit/cli_test.py

pgctl provides a pre-start hook to run some user defined set up before launching playground services. If those user defined actions involve modifying some state, there isn't currently an easy way to clean up those modifications when the playground stops. This PR adds a hook that runs after all services in a playground have stopped.

Add post stop hook

---

pgctl/poll_ready.py
tests/spec/unreliable.py

The sleep in pgctl-poll-ready is not accurate and can cause some parts of the test suite to flake. This branch replaces the counting sleep loop with one that uses a time diff instead. It also fixes some hard coded time values in tests.

Fixed inaccurate sleep in poll_ready and other test issues.

---

pgctl/poll_ready.py
test
tox.ini

Fixes a race condition where the supervised service can start and die without a down notification being received by poll-ready. The details of the race are as follows (line # from original code):
1. Parent: L112 runs and S6 begins supervising the service
2. Parent: The service exits (nonzero code) and S6 sends the down notification
3. Child: L131 executes and the process subscribes to S6 notifications
4. The child never receives the down from step 2 because it wasn't listening soon enough.
A fix for that is to create the notification fifo prefork.
Note: after spending a bit of time trying to repro the race condition in a test, it seemed like that wasn't worth it (since the test would flake / false negative). Interactive testing with a known problem playground shows that this seems to have …

Fixed race condition that left zombie poll readies.

---

pgctl/cli.py
tests/examples/pre-start-hook/playground/pre-start
tests/spec/debug.py
tests/spec/examples.py

A couple fixes for interaction between pre-start/post-stop and pgctl debug:
1. Do not run post-stop if a service is being shut down to enter debug mode.
2. Run pre-start prior to entering debug mode on a stopped service.
Internal ticket COREBACK-1796

pgctl debug and pre-start/post-stop fixes

---

pgctl/fuser.py
tests/spec/fuser.py

Tests are broken, first submitting this as an RFC. The scenario is to provide some way to cleanup playgrounds if the playground directory itself has been deleted, which is not too uncommon for automated builds.
A cleanup script would identify old playgrounds via `ycp list`. Non ycp users could do something with just pgrep s6-supervise and extracting the PGCTL_SERVICE environment variable.
Once you have the playground path, call `pgctl-fuser -d <playground_dir> | xargs kill -9`
Internal ticket COREBACK-2143

add allow-deleted option to fuser

---

pgctl/service.py

Set PGCTL_* env. vars. for s6-log processes.

---

docs/source/user/quickstart.rst
pgctl/functions.py
tests/spec/dirty_tests.py

The hint message is incorrect --
> There are two ways you can fix this:
>   * temporarily: pgctl stop --force playground/sweet
>   * permanently: http://pgctl.readthedocs.org/en/latest/user/quickstart.html#writing-playground-services
"--force" is an optional argument while "stop" and "playground/sweet" are positional arguments; optional arguments cannot appear in between positional ones.  The pgctl command should instead be `pgctl --force stop playground/sweet` or `pgctl stop playground/sweet --force`.

Fix incorrect hint messages about force stop

---

.pre-commit-config.yaml
docs/source/index.rst
docs/source/user/install.rst
docs/source/user/quickstart.rst
docs/source/user/usage.rst
pgctl/service.py
requirements.d/test.txt
tests/examples/post-stop-hook/playground/B/run

Send a SIGKILL to s6-log instead of a SIGTERM. Also disable multiline buffering in s6-log to reduce the potential for log line loss that could occur due to SIGKILLing.

Send a SIGKILL to s6-log instead of a SIGTERM (fixed #194).

---

pgctl/cli.py
tests/unit/cli_test.py

Also use timeout_stop for a stop action instead of timeout_ready.

Fixed a test flake due to #195.

---

pgctl/config.py

This resolves issues with text/bytes type mismatches in Python 2, and improves
safety when loading yaml files.

Load pgctl.yaml files in a safer way (fixes #203).

---

.pre-commit-config.yaml
Makefile
tests/spec/examples.py
tests/testing/norm.py
tests/unit/functions.py

Most of this is straightforward and normal. Weirdest thing is that python 3.4+ changed behavior for file descriptors being passed to subprocesses.

Fix build under python 3.6

---

.github/workflows/ci.yml
pgctl/cli.py
pgctl/telemetry.py
setup.py
tests/spec/cli.py
tests/spec/examples.py
tests/unit/telemetry_test.py

This adds some basic telemetry functionality to pgctl, backed by `yelp-clog` (scribe/monk). This is optional and disabled by default.
To enable it, one needs to have `yelp-clog` installed (e.g. by installing the new `pgctl[telemetry]` extra) and enable it explicitly in the pgctl config. This can be done by putting a file at `/etc/pgctl.json`, `~/.pgctl.json`, or `pgctl.json` in your working directory with contents like:
```json
{
"telemetry": true,
"telemetry_clog_config_path": "/etc/clog.yaml"
}
```
The motivation behind this is that we will soon be doing some improvements to try to make pgctl more resilient to poorly-behaving processes or unexpected user behavior, and we want to be able to measure if those changes are working. We will probably enable it by default on our boxes with …

Add basic telemetry

---

setup.py

Old versions don't implement `__fspath__` on py.path objects and cause a crash like this:
```
$ pgctl stop
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "xxx/virtualenv_run/lib/python3.7/site-packages/pgctl/__main__.py", line 4, in <module>
exit(main())
File "xxx/virtualenv_run/lib/python3.7/site-packages/pgctl/cli.py", line 738, in main
return app()
File "xxx/virtualenv_run/lib/python3.7/site-packages/pgctl/cli.py", line 222, in __call__
result = command()
File "xxx/virtualenv_run/lib/python3.7/site-packages/pgctl/cli.py", line 470, in stop
failed = self.__change_state(Stop, self.services)
File …
```

Require py>=1.4.32

---

pgctl/cli.py
pgctl/functions.py
pgctl/log_viewer.py
pgctl/service.py
setup.cfg
tests/examples/slow-startup/playground/slow-startup/service
tests/spec/examples.py
tests/spec/slow_startup.py
tests/unit/functions.py
tests/unit/log_viewer_test.py

This adds an embedded log viewer during `pgctl start` and `pgctl stop` which tails the logs of the services being started or stopped. The idea is to help users understand what is going on when pgctl takes a long time to start or stop things.
It looks like this:
https://user-images.githubusercontent.com/665269/140195366-dc4e135f-7fee-4c21-a88e-5aa511fc8b7a.mov
There is some concern that all the new output may be confusing to users or make them think something is wrong. I tried to adjust the output a bit to improve this, but there is surely future room for improvement.
It is enabled by default but can be disabled via config option (per-project, per-user, or per-host), so we can turn it off if it causes problems.

Add an embedded log viewer during start/stop

---

pgctl/log_viewer.py
tests/unit/log_viewer_test.py

We were already providing a fallback terminal width, but it turns out that it's still possible to get a zero terminal width without it producing an actual error.
Internal ticket: CORESERV-11279

Don't error when the terminal width is zero

---

pgctl/cli.py
pgctl/functions.py
pgctl/service.py
tests/spec/dirty_tests.py

Currently `pgctl start` will crash with a confusing error message if there are any processes holding the s6 lock (but no `s6-supervise` command running). This is happening a few times per day according to our telemetry and we sometimes get reports about the hard-to-understand and hard-to-fix error.
After this change, any unsupervised processes (detected via both s6 lock file and environment variable tracing) will be terminated if the service is unsupervised. This will reduce errors from pgctl _and_ confusing errors in cases where the orphaned process is holding a resource (like a port) that causes the new process to crash loop.

Force kill any unsupervised processes at the start
