Yelp/pgctl

pgctl/cli.py, tests/main_test.py
This change is meant to support all command line arguments mentioned in the [spec](https://docs.google.com/document/d/15SXwQ4OFPRklkwxUdw7HFL6GAae_lEUhp1iOkLsUlZU/edit#heading=h.ruokevxq1gj6).
=> expand the list of supported commands

.travis.yml
=> coveralls fixed.

.activate.sh, .coveragerc, pgctl/cli.py, pgctl/config.py, test, tests/conftest.py, tests/examples/date/playground/config.yaml, tests/integration/cli.py, tests/integration/examples.py, tests/testing/__init__.py, tests/unit/cli.py, tests/unit/flock.py
svc does not report an error code when a service does not exist, this commit raises an IOERROR and adds tests.
-fix svc doesn't have error code
-fix deadlock due to long running service and trying to read from stdout, stderr
-fix start doesn't throw an error when the service doesn't exist
-fix .coverage files don't combine when tests fail
=> Fix start cmd, fake service

pgctl/cli.py, setup.py, tests/examples/multiple/playground/conf.yaml, tests/examples/multiple/playground/date/run, tests/examples/multiple/playground/tail/run, tests/integration/cli.py, tests/integration/examples.py
Starting and stopping for multiple services.
=> Multiple services

pgctl/cli.py, pgctl/service.py, tests/unit/service.py
Based on feedback from @bukzor in another review.
=> Refactor Service arguments

pgctl/cli.py, requirements.d/test.txt, requirements.d/travis.txt, test, tests/conftest.py
This revealed a couple subprocess issues which I've fixed at the same time.
=> test with parallel processes, by default

docs/source/developer/design.rst, docs/source/index.rst
[doc link](http://kentwills-pgctl.readthedocs.org/en/developer_docs/developer/design.html)
=> add developer docs

pgctl/cli.py, tests/spec/cli.py, tests/spec/examples.py
=> pgctl-2015 works in any dir

docs/source/user/quickstart.rst, pgctl/functions.py, tests/implementation/functions.py, tests/spec/examples.py
=> GH-62 Replace fuser with lsof

.activate.sh, .deactivate.sh, pgctl/daemontools.py, pgctl/service.py, test, tests/spec/slow_startup.py
=> parser is now more rigorous, and simpler

.coveragerc, pgctl/__init__.py, pgctl/cli.py, pgctl/errors.py, pgctl/flock.py, pgctl/functions.py, pgctl/service.py, test, tests/examples/slow-shutdown/playground/sweet/run, tests/spec/dirty_tests.py, tests/spec/slow_startup.py
* stopping is faster
* improved the error messaging in the slow-lsof case
=> Messaging moar3

docs/source/conf.py, pgctl/cli.py, pylintrc, tests/unit/config.py
=> Fix bitrot

.pre-commit-config.yaml, .travis.yml, pgctl/cli.py, pgctl/config.py, pgctl/daemontools.py, pgctl/debug.py, pgctl/flock.py, pgctl/functions.py, pgctl/poll_ready.py, pgctl/service.py, pgctl/subprocess.py, pgctl/timestamp.py, pylintrc, tests/conftest.py, tests/spec/cli.py, tests/spec/config.py, tests/spec/debug.py, tests/spec/dirty_tests.py, tests/spec/examples.py, tests/spec/parallel.py, tests/testing/norm.py, tests/testing/subprocess.py, tests/unit/flock.py, tests/unit/functions.py, tox.ini
=> Python three support

.coveragerc, pgctl/__init__.py, pgctl/cli.py, pgctl/errors.py, pgctl/flock.py, pgctl/service.py, pylintrc, tests/spec/parallel.py, tests/testing/norm.py
=> improved error messaging, in the "another pgctl" case

pgctl/cli.py, pylintrc, tests/spec/dirty_tests.py, tests/spec/parallel.py, tests/spec/slow_startup.py
=> Provide more context on failures

docs/source/index.rst, pgctl/poll_ready.py, setup.py, tests/examples/dependent/playground/A/run, tests/spec/cli.py, tests/spec/debug.py, tests/spec/dirty_tests.py, tests/spec/examples.py, tests/spec/parallel.py, tests/spec/slow_startup.py, tests/spec/unreliable.py
=> Rename pgctl-2015 => pgctl

RELEASE.md, pgctl/__init__.py
Would like signoff from @chriskuehl
=> This is v2.0.0

pgctl/cli.py
=> Don't scientific notation

.activate.sh, .deactivate.sh
=> Stop doing crazy things in .activate.sh

pgctl/cli.py, tests/spec/cli.py, tests/spec/examples.py
=> Add pgctl status --json

pgctl/cli.py, pylintrc, requirements.d/dev.txt, tests/spec/examples.py, tests/testing/norm.py, tests/unit/cli_test.py
Opening this as a request for comments. It's kinda hard to use color without looking gimmicky or overusing it, but I think this is helpful?
Tests and such will fail for now, I'll wait for some feedback before I go fix all of that.
=> Make 'pgctl status' more colorful

pgctl/cli.py, tests/spec/debug.py, tests/spec/examples.py
=> Make state changes a no-op if already in that state

pgctl/service.py, tests/spec/examples.py
Fixes #134
i keep running into this lol
=> Fix "pgctl log" creating new services

tests/testing/subprocess.py
=> Actually assert the returncode in tests

pgctl/poll_ready.py, tests/examples/poll-ready-quick-shutdown/playground/readyservice/ready, tests/examples/poll-ready-quick-shutdown/playground/readyservice/run, tests/examples/poll-ready-quick-shutdown/playground/readyservice/service, tests/spec/poll_ready_quick_shutdown.py
=> Fix poll ready stop delays

pgctl/poll_ready.py, tests/spec/examples.py
Fixes #171 and makes the test suite green under Py 3.5.
=> Fixed string/bytes comparisons under py3.x in poll-ready and the tests

docs/source/user/quickstart.rst, pgctl/functions.py, tests/spec/dirty_tests.py
=> Fix recommended stop --force command

.pre-commit-config.yaml, docs/source/conf.py, pgctl/configsearch.py, pgctl/poll_ready.py, tests/spec/configsearch.py, tests/unit/configsearch.py
=> Remove "security" features
